name: Renovate
on:
  # schedule:
  #   - cron: "23 2 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: renovatebot/github-action@v46.1.17
        # env:
        #   LOG_LEVEL: debug
        with:
          token: ${{ secrets.GH_FINE_GRAINED_PAT }}
          configurationFile: config.js
